apiVersion: v1
kind: Service
metadata:
  name: red
spec:
  selector:
    color: red # match the rc metadata lable
  type: NodePort
  ports:
    - name: http
      nodePort: 31001 # expose at the node level
      port: 80 # expose within the cluster
      targetPort: 8080 # what is being routed to the appropriate part
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: green
spec:
  selector:
    color: green
  type: NodePort
  ports:
    - name: http
      nodePort: 31002
      port: 80
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: blue
spec:
  selector:
    color: blue
  type: NodePort
  ports:
    - name: http
      nodePort: 31003
      port: 80
      targetPort: 8080
      protocol: TCP
